name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Enable Corepack
        run: corepack enable

      - name: Set pnpm version to 10.17.0
        run: corepack prepare pnpm@10.17.0 --activate

      - name: Verify pnpm Version
        run: pnpm --version

      - name: Clear pnpm Cache
        run: pnpm cache delete

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Build the project
        run: pnpm build

      - name: Deploy to GitHub Pages on gh-pages branch
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./out # Next.js static export output directory
